Repository agri-gaia/seerep, pull requests merged in 2022-08, with the labels that each got.

#143 fix: typo in server config
  seerep.cfg
Labels: bug

#144 fix example scripts
  docker/base/Dockerfile
  examples/gRPC/images/gRPC_fb_queryImage.py
  examples/gRPC/images/gRPC_pb_queryImage.py
  examples/gRPC/images/gRPC_pb_queryImageGrid.py
  examples/gRPC/images/gRPC_pb_sendLabeledImage.py
  examples/gRPC/images/gRPC_pb_sendLabeledImageGrid.py
Labels: bug

#149 Fix/example scripts server uri
  .gitignore
  .isort.cfg
  certs/ca.crt
  certs/ca.key
  certs/tls.pem
  examples/gRPC/images/gRPC_fb_queryImage.py
  examples/gRPC/images/gRPC_pb_queryImage.py
  examples/gRPC/images/gRPC_pb_queryImageGrid.py
  examples/gRPC/images/gRPC_pb_sendLabeledImage.py
  examples/gRPC/images/gRPC_pb_sendLabeledImageGrid.py
  examples/gRPC/meta/gRPC_fb_getProjects.py
  examples/gRPC/meta/gRPC_pb_createProject.py
  examples/gRPC/meta/gRPC_pb_getProjects.py
  examples/gRPC/simulated-data/loadSimulatedData.py
  examples/gRPC/simulated-data/querySimulatedData.py
  examples/gRPC/tf/gRPC_pb_queryFrames.py
  examples/gRPC/tls.pem
  examples/gRPC/util.py
Labels: api

#123 include progress into MkDocs
  .devcontainer/devcontainer.json
  .mdl_style.rb
  docs/mkdocs/getting-started/docs.md
  docs/mkdocs/getting-started/installation.md
  docs/mkdocs/getting-started/tests.md
  docs/mkdocs/home/index.md
  docs/mkdocs/installation.md
  docs/mkdocs/reference/packages.md
  docs/mkdocs/tutorials-c++.md
  docs/mkdocs/tutorials-python.md
  docs/mkdocs/tutorials/images.md
  docs/mkdocs/tutorials/overview.md
  docs/mkdocs/tutorials/projects.md
  examples/python/drawLabelsInImage.py
  examples/python/gRPC/instances/gRPC_fb_getInstances.py
  examples/python/gRPC/meta/gRPC_fb_getProjects.py
  examples/python/gRPC/meta/gRPC_pb_createProject.py
  examples/python/gRPC/meta/gRPC_pb_getProjects.py
  examples/python/gRPC/point/gRPC_fb_sendPointsBasedOnImageInstances.py
  examples/python/gRPC/util_fb.py
  mkdocs.yml
Labels: documentation

#154 fix: mkdocs deployment due to different folder structure
  docs/gh-pages/index.html
Labels: bug, documentation

#155 add deployment to docs
  docs/mkdocs/getting-started/installationDev.md
  docs/mkdocs/getting-started/kubernetes-deployment.md
  docs/mkdocs/getting-started/local-deployment.md
  mkdocs.yml
Labels: documentation

#159 Feature/extend query
  .devcontainer/.vscode/tasks.json
  .devcontainer/devcontainer.json
  examples/python/gRPC/images/gRPC_fb_queryImage.py
  seerep-hdf5/seerep-hdf5-fb/include/seerep-hdf5-fb/hdf5-fb-image.h
  seerep-hdf5/seerep-hdf5-fb/src/hdf5-fb-general.cpp
  seerep-hdf5/seerep-hdf5-fb/src/hdf5-fb-image.cpp
  seerep-msgs/core/query.h
  seerep-msgs/fbs/query.fbs
  seerep-srv/seerep-core-fb/include/seerep-core-fb/core-fb-conversion.h
  seerep-srv/seerep-core-fb/src/core-fb-conversion.cpp
  seerep-srv/seerep-core-fb/src/core-fb-image.cpp
  seerep-srv/seerep-core/include/seerep-core/core-dataset.h
  seerep-srv/seerep-core/src/core-dataset.cpp
Labels: api, core

#167 remove auto return type in seerep_hdf5_fb tests
  seerep-hdf5/seerep-hdf5-fb/test/fb-write-load-test.cpp
Labels: enhancement, test
