Repository agri-gaia/seerep, pull requests merged in 2023-02, with the labels that each got.

#252 parse environment vars
  seerep-srv/seerep-server/include/seerep-server/server.h
  seerep-srv/seerep-server/src/server.cpp
Labels: general

#255 server program_options: env vars in docker compose
  README.md
  docker/docker-compose.yml
  docs/mkdocs/getting-started/server/configuration.md
  docs/mkdocs/getting-started/server/installationDev.md
  docs/mkdocs/getting-started/server/kubernetes-deployment.md
  docs/mkdocs/getting-started/server/local-deployment.md
  seerep-srv/seerep-server/src/server.cpp
Labels: documentation

#259 Bump NumPy to fix vulnerabilities
  docker/base/requirements.txt
Labels: enhancement
